version: '2'
services:

  jenkins-dood:
    image: jenkins-dood
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./jenkins_home/jobs:/var/jenkins_home/jobs
    ports:
      - 99:8080
